"""add crack_time to history

Revision ID: ee4098cd0b39
Revises: b3ab11907142
Create Date: 2026-03-26 21:48:02.142238

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee4098cd0b39'
down_revision: Union[str, Sequence[str], None] = 'b3ab11907142'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('check_history', sa.Column('crack_time', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('check_history', 'crack_time')
    # ### end Alembic commands ###
